"""lookup_script_api.py: the scripting API's interfaces and members, with the file and line of each."""
from tests.skill_helpers import REPO, install, new_project, tool

TS_DEFS = f"{REPO.as_posix()}/data/c3-ts-defs"    # the header line prints the declaration's file as a posix path


def test_an_addon_by_name_prints_its_interface_and_what_it_extends(built):
    code, out = tool(built, "lookup_script_api", "Timer")
    assert code == 0
    assert out.startswith(f"class ITimerBehaviorInstance   {TS_DEFS}/behaviors/general/timer/")
    assert "  startTimer(duration: number, name: string, type?: TimerBehaviorTimerType): void;" in out
    assert "members of IBehaviorInstance are ITimerBehaviorInstance's too" in out


def test_a_member_prints_its_interface_declaration_and_doc(built):
    """A member of an instance, such as runtime.callFunction, prints its interface, declaration and doc comment."""
    code, out = tool(built, "lookup_script_api", "runtime.callFunction")
    assert code == 0
    assert out.startswith(f"IRuntime.callFunction   {TS_DEFS}/preview/interfaces/IRuntime.d.ts:")
    assert "callFunction(name: string, ...params: CallFunctionParameter[]): CallFunctionReturnValue;" in out
    assert "/** Call a function in an event sheet" in out


def test_a_member_of_an_interface_is_found_where_it_is_inherited_from(built):
    code, out = tool(built, "lookup_script_api", "ISpriteInstance.x")
    assert code == 0 and out.startswith("IWorldInstance.x   ") and "  x: number;" in out
    code, out = tool(built, "lookup_script_api", "ISpriteInstance.speed")
    assert code == 1
    assert "ISpriteInstance and the interfaces it extends declare no 'speed'" in out


def test_a_size_member_says_what_it_measures(built):
    # The viewport's size is not the layout's, and a sprite's image size is not the instance's
    code, out = tool(built, "lookup_script_api", "runtime.viewportWidth", "ISpriteInstance.imageWidth")
    assert code == 0
    assert "  readonly viewportWidth: number;\n  -- the project's viewport size" in out, out
    assert "runtime.layout.width" in out and "not the instance's size in the layout" in out, out
    code, out = tool(built, "lookup_script_api", "IRuntime")
    lines = out.splitlines()
    notes = [i for i, line in enumerate(lines) if line.startswith("  -- the project's viewport size")]
    assert len(notes) == 1 and lines[notes[0] - 1] == "  getViewportSize(): Vec2Arr;", out


def test_a_name_the_api_does_not_declare_prints_the_near_ones(built):
    code, out = tool(built, "lookup_script_api", "callFuncton")
    assert code == 1 and out.startswith("the scripting API declares no 'callFuncton'; closest: callFunction")
    code, out = tool(built, "lookup_script_api", "tick")
    assert code == 0 and "members whose name holds it" in out and "IRuntime.tickCount" in out


INSTANCE_TYPES = """// NOTE: this file is auto-generated by Construct
declare namespace InstanceType {
\tclass __CoinBehaviors<InstType> {
\t\tTween: ITweenBehaviorInstance<InstType>;
\t}
\tclass Coin extends ISpriteInstance {
\t\tbehaviors: __CoinBehaviors<this>;
\t}
}
"""


def test_the_project_types_the_editor_wrote_are_searched(tmp_path):
    """open_in_editor.py --typescript writes the project's objects, as the editor words them, beside a copy of
    the whole API, which is read from the clone alone."""
    root = new_project(tmp_path / "game")
    assert install(root)[0] == 0
    defs = root / "scripts" / "ts-defs"
    (defs / "runtime").mkdir(parents=True)
    (defs / "instanceTypes.d.ts").write_text(INSTANCE_TYPES, encoding="utf-8")
    (defs / "runtime" / "IRuntime.d.ts").write_text("declare class IRuntime {\n\tcallFunction(): void;\n}\n",
                                                   encoding="utf-8")
    code, out = tool(root, "lookup_script_api", "Coin")
    assert code == 0
    assert "class InstanceType.Coin   scripts/ts-defs/instanceTypes.d.ts:6\n  class Coin extends ISpriteInstance" in out
    assert "class InstanceType.__CoinBehaviors   scripts/ts-defs/instanceTypes.d.ts:3" in out
    code, out = tool(root, "lookup_script_api", "InstanceType.Coin.x")
    assert code == 0 and out.startswith("IWorldInstance.x   ")
    code, out = tool(root, "lookup_script_api", "callFunction")
    assert code == 0 and out.count("IRuntime.callFunction   ") == 1 and "scripts/ts-defs/runtime" not in out
